name: 🍏 iOS Builds
on:
  workflow_call:

# Global Settings
env:
  # Only used for the cache key. Increment version to force clean build.
  ACTIVE_BASE_BRANCH: 3.6
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-ios
  cancel-in-progress: true

jobs:
  ios-template:
    runs-on: "macos-latest"
    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v4

      - name: Restore Active build cache
        uses: ./.github/actions/active-cache-restore
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/active-deps

      - name: Compilation (arm64v8)
        uses: ./.github/actions/active-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: iphone
          target: release
          tools: false

      - name: Save Active build cache
        uses: ./.github/actions/active-cache-save
        continue-on-error: true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
